### ISSUE TITLE
doesn't work in blender 4.0 beta

### ISSUE THREAD

**Issue by OrlandaPrime** [BlenderDefender/Gizmodal-Ops#10]
**Describe the bug**
Gizmo aren't activated in blender 4.0 beta.

**System Information (please complete the following information):**
- OS: windows 11
- Blender Version: 4.0 beta
- Addon Version: 1.0.0

**Comment by BlenderDefender** [comment]
Thank you for the report, I'll have a look at this issue as soon as possible.

**Comment by BlenderDefender** [comment]
Related to #12

**Comment by BlenderDefender** [comment]
Alright, I think I've found and fixed the problem. You can download the updated version from the repository page now. Please let me know, if there are any further issues. I'll test everything myself and publish the fix soon, if everything works well.
