### ISSUE TITLE
Does not work on Blender 4.0 Official Release 

### ISSUE THREAD

**Issue by Polar7454** [BlenderDefender/Gizmodal-Ops#12]
**Description of the bug:**
As the title suggests, currently not working on the Blender 4.0 official release. The gizmo isn't appearing when pressing G, R or S. Settings tab is still available in the N-panel(view). The functionality of gizmos appearing on the objects is missing with the new official update of Blender 4.0. Is working fine with Blender 3.6 release though.

**System Information:**
- OS: [Windows 10]
- Blender Version: [4.0]
- Addon Version: [1.0.0]

**Comment by raji08081222** [comment]
Hi BlenderDefender! I love this addon. I would appreciate it if you could address this issue. Personally, I don't mind paying for it.

**Comment by rpeticcagpd** [comment]
Hello I am having the same issue. This is my favorite plug in for Blender

**Comment by werwack** [comment]
Same here... This is very sad, it is also my favorite one. Thanks for any help

**Comment by BlenderDefender** [comment]
Alright everybody, I think I've found and fixed the problem. You can download the updated version from the repository page now. Please let me know, if there are any further issues. I'll test everything myself and publish the fix soon, if everything works well. Thank you very much for your patience.

**Comment by raji08081222** [comment]
Hellow BlenderDefender. I was looking forward to it. It's working fine so far. Thank you for your sincere response! I hope that all your days are filled with happiness！

**Comment by werwack** [comment]
The fix works like a charm for me too.
Thanks a lot!!!!

**Comment by rpeticcagpd** [comment]
It worked for me! Blender is completely unusable with out your tool! Thank you so much
