### ISSUE TITLE
Error after deactivating the addon: 'bpy_prop_collection[key]: key "UV Editor" not found'

### ISSUE THREAD

**Issue by xan2622** [BlenderDefender/Gizmodal-Ops#6]
**Describe the bug**
An error appears when I try to deactivate the add-on.

**To Reproduce**
1. After the add-on is installed and Blender preferences are saved, quit Blender
2. Relaunch Blender
3. Now, try to deactivate the add-on

**Expected behavior**
The add-on should just deactivate.

**System Information (please complete the following information):**
 - OS: Windows 11 
 - Blender Version: 3.2.0 stable
 - Addon Version: 1.0.0

**Error**

> Traceback (most recent call last):
>  File "E:\Blender_Builds\stable\blender-3.2.0+stable.e05e1e369187\3.2\scripts\modules\addon_utils.py", line 423, in disable
    mod.unregister()
>  File "C:\Users\xan2622\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Gizmodal-Ops\__init__.py", line 129, in unregister
>    unregister_keymap()
>  File "C:\Users\xan2622\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Gizmodal-Ops\__init__.py", line 87, in unregister_keymap
>    active_km = wm.keyconfigs.active.keymaps[map]
> KeyError: 'bpy_prop_collection[key]: key "UV Editor" not found'

**Comment by BlenderDefender** [comment]
Just for the context: Do you use the default Blender Keymap or do you use a custom Keymap?

**Comment by xan2622** [comment]
I use a custom keymap.

**Comment by BlenderDefender** [comment]
Ah, ok. I've got an idea why disabling Gizmodal Ops doesn't work then. Give me a minute.

**Comment by BlenderDefender** [comment]
So, I've uploaded a commit that should fix the issue. You can download it from https://github.com/BlenderDefender/Gizmodal-Ops/archive/refs/heads/6-error-after-deactivating-the-addon.zip
Let me know if that works.

**Comment by xan2622** [comment]
It works. Thanks a lot.

**Comment by BlenderDefender** [comment]
> Have you considered publishing your addons on **https://blenderartists.org/c/coding/released-scripts-and-themes/50** ? It's a very known forum, it could increase your audience (users).
Not yet, but thank you for the tip.
